name: go-tests
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'v[0-9]+.[0-9]+.[0-9]+'
    pull_request_target:
        types: [labeled, opened, synchronize, reopened]
        paths:
            - "pkg/**"

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [1.21.x]
        steps:
            # begin: setup
            # TODO: Extra into action composition https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
            - name: Free Disk Space (Ubuntu)
              uses: jlumbroso/free-disk-space@main
              with:
                tool-cache: false
                android: true
                dotnet: true
                haskell: true
                large-packages: false
                swap-storage: true
                docker-images: false
            # end: setup

            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                path: go-codegenerator
            - name: Setup Go ${{ matrix.go-version }}
              uses: actions/setup-go@v4
              with:
                go-version: ${{ matrix.go-version }}
            - name: Get dependencies
              run: |
                cd go-codegenerator && go install github.com/mgechev/revive@latest
            - name: Run tests
              run: |
                cd go-codegenerator && go test -v ./... 
            - name: Run lintinh
              run: |
                cd go-codegenerator && revive -formatter friendly ./...